logging:
    config: classpath:logback.xml
server:
    port: 8081

xxl:
    job:
        accessToken:
        admin:
            addresses: http://172.21.10.95:8088/dschedule
        executor:
            appname: dwaybill
            ip:
            logpath: ~/data/applogs/xxl-job/jobhandler/
            port: 9998

#httpClient连接管理配置
http:
    maxTotal: 20
    defaultMaxPerRoute: 20
    connectTimeout: 1000
    connectionRequestTimeout: 500
    socketTimeout: 10000
    staleConnectionCheckEnabled: true
waybill:
  baseUrl: http://210.16.188.129:24099


spring:
   jpa:
      hibernate:
        ddl-auto: none

   profiles:
     active: @active.profile@



