spring:
   jpa:
      database-platform: org.hibernate.dialect.OracleDialect
      database: ORACLE
      show-sql: true
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: true
         hibernate.cache.use_query_cache: false
         hibernate.generate_statistics: false
        # hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
   ##配置数据库连接
   datasource:
      url: jdbc:oracle:thin:@192.168.184.121:1521:tes
      username: tes
      password: tes