logging:
    config: classpath:logback.xml
server:
    port: 8081

xxl:
    job:
        accessToken:
        admin:
            addresses: http://172.21.10.95:8088/dschedule
        executor:
            appname: dwaybill
            ip:
            logpath: ~/data/applogs/xxl-job/jobhandler/
            port: 9998

#httpClient连接管理配置
http:
    maxTotal: 20
    defaultMaxPerRoute: 20
    connectTimeout: 1000
    connectionRequestTimeout: 500
    socketTimeout: 10000
    staleConnectionCheckEnabled: true
waybill:
  baseUrl: http://210.16.188.129:24099


spring:
   jpa:
      hibernate:
        ddl-auto: none

      database-platform: org.hibernate.dialect.OracleDialect
      database: ORACLE
      show-sql: true
      properties:
         hibernate.id.new_generator_mappings: true
         hibernate.cache.use_second_level_cache: true
         hibernate.cache.use_query_cache: false
         hibernate.generate_statistics: false
        # hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
   ##配置数据库连接
   datasource:
      url: jdbc:oracle:thin:@192.168.184.28:1532:dposdev
      username: dpos
      password: dpos



